# Generated by Django 5.0 on 2026-08-07 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='static_after',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='project',
            name='static_before',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='project',
            name='static_featured',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='project',
            name='after_image',
            field=models.ImageField(blank=True, null=True, upload_to='projects/after/'),
        ),
        migrations.AlterField(
            model_name='project',
            name='before_image',
            field=models.ImageField(blank=True, null=True, upload_to='projects/before/'),
        ),
        migrations.AlterField(
            model_name='project',
            name='featured_image',
            field=models.ImageField(blank=True, null=True, upload_to='projects/featured/'),
        ),
    ]
