# Generated by Django 5.0 on 2026-07-15 18:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="CompanyInfo",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        default="Michael Aluminum and Glass Technology", max_length=255
                    ),
                ),
                (
                    "tagline",
                    models.CharField(
                        default="Building the Future with Premium Aluminum & Glass Solutions",
                        max_length=500,
                    ),
                ),
                ("description", models.TextField()),
                ("email", models.EmailField(max_length=254)),
                ("phone", models.CharField(max_length=20)),
                ("whatsapp", models.CharField(blank=True, max_length=20)),
                ("telegram", models.CharField(blank=True, max_length=50)),
                ("facebook", models.URLField(blank=True)),
                ("instagram", models.URLField(blank=True)),
                ("linkedin", models.URLField(blank=True)),
                ("youtube", models.URLField(blank=True)),
                ("address", models.TextField()),
                ("city", models.CharField(max_length=100)),
                ("country", models.CharField(max_length=100)),
                ("years_experience", models.IntegerField(default=10)),
                ("projects_completed", models.IntegerField(default=500)),
                ("happy_clients", models.IntegerField(default=200)),
                ("team_members", models.IntegerField(default=25)),
                (
                    "logo",
                    models.ImageField(blank=True, null=True, upload_to="company/"),
                ),
                (
                    "favicon",
                    models.ImageField(blank=True, null=True, upload_to="company/"),
                ),
                (
                    "hero_image",
                    models.ImageField(blank=True, null=True, upload_to="hero/"),
                ),
                ("meta_description", models.CharField(max_length=160)),
                ("meta_keywords", models.CharField(max_length=255)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Company Information",
                "verbose_name_plural": "Company Information",
            },
        ),
        migrations.CreateModel(
            name="SiteSettings",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("enable_dark_mode", models.BooleanField(default=True)),
                ("enable_newsletter", models.BooleanField(default=True)),
                ("enable_live_chat", models.BooleanField(default=True)),
                ("maintenance_mode", models.BooleanField(default=False)),
                ("default_language", models.CharField(default="en", max_length=10)),
                ("enable_amharic", models.BooleanField(default=True)),
                ("enable_tigrinya", models.BooleanField(default=True)),
                ("google_analytics_id", models.CharField(blank=True, max_length=50)),
                ("cloudinary_cloud_name", models.CharField(blank=True, max_length=255)),
                ("cloudinary_api_key", models.CharField(blank=True, max_length=255)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Site Settings",
                "verbose_name_plural": "Site Settings",
            },
        ),
        migrations.CreateModel(
            name="StatisticCard",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=100)),
                ("value", models.CharField(max_length=50)),
                ("description", models.CharField(max_length=200)),
                (
                    "icon",
                    models.CharField(
                        help_text="Font Awesome icon class", max_length=100
                    ),
                ),
                ("order", models.IntegerField(default=0)),
                ("is_active", models.BooleanField(default=True)),
            ],
            options={
                "verbose_name": "Statistic Card",
                "verbose_name_plural": "Statistic Cards",
                "ordering": ["order"],
            },
        ),
        migrations.CreateModel(
            name="WhyChooseUsCard",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=100)),
                ("description", models.TextField()),
                (
                    "icon",
                    models.CharField(
                        help_text="Font Awesome icon class", max_length=100
                    ),
                ),
                ("order", models.IntegerField(default=0)),
                ("is_active", models.BooleanField(default=True)),
            ],
            options={
                "verbose_name": "Why Choose Us Card",
                "verbose_name_plural": "Why Choose Us Cards",
                "ordering": ["order"],
            },
        ),
    ]
