# Generated by Django 5.0 on 2026-08-07 13:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0003_make_service_fields_optional'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='static_image',
            field=models.CharField(blank=True, help_text='Path relative to static folder e.g. images/Category 1 Handrail/photo.jpg', max_length=255),
        ),
    ]
