# Generated by Django 5.0 on 2026-07-15 18:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Testimonial",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("client_name", models.CharField(max_length=200)),
                (
                    "client_title",
                    models.CharField(
                        blank=True, help_text="e.g., Project Manager", max_length=200
                    ),
                ),
                ("client_company", models.CharField(max_length=200)),
                (
                    "client_photo",
                    models.ImageField(blank=True, upload_to="testimonials/"),
                ),
                ("review", models.TextField()),
                (
                    "rating",
                    models.IntegerField(
                        choices=[(1, "1"), (2, "2"), (3, "3"), (4, "4"), (5, "5")],
                        default=5,
                    ),
                ),
                (
                    "project_link",
                    models.CharField(
                        blank=True,
                        help_text="Link to associated project",
                        max_length=200,
                    ),
                ),
                ("is_featured", models.BooleanField(default=False)),
                ("order", models.IntegerField(default=0)),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Testimonial",
                "verbose_name_plural": "Testimonials",
                "ordering": ["-is_featured", "-order", "-created_at"],
            },
        ),
    ]
