# Generated by Django 5.0 on 2026-07-15 18:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Quotation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("full_name", models.CharField(max_length=200)),
                ("company", models.CharField(blank=True, max_length=200)),
                ("email", models.EmailField(max_length=254)),
                ("phone", models.CharField(max_length=20)),
                ("service_needed", models.CharField(max_length=200)),
                ("project_location", models.CharField(max_length=300)),
                ("project_description", models.TextField()),
                (
                    "budget",
                    models.CharField(
                        blank=True, help_text="e.g., Budget Range", max_length=100
                    ),
                ),
                ("expected_completion_date", models.DateField(blank=True, null=True)),
                (
                    "drawings",
                    models.FileField(blank=True, upload_to="quotations/drawings/"),
                ),
                (
                    "additional_files",
                    models.FileField(blank=True, upload_to="quotations/files/"),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("reviewing", "Under Review"),
                            ("quoted", "Quoted"),
                            ("completed", "Completed"),
                            ("rejected", "Rejected"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                ("notes", models.TextField(blank=True, help_text="Internal notes")),
                ("assigned_to", models.CharField(blank=True, max_length=200)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Quotation",
                "verbose_name_plural": "Quotations",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="QuotationResponse",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("quote_number", models.CharField(max_length=50, unique=True)),
                ("quote_amount", models.DecimalField(decimal_places=2, max_digits=12)),
                ("currency", models.CharField(default="USD", max_length=3)),
                ("description", models.TextField()),
                ("scope_of_work", models.TextField()),
                ("terms_conditions", models.TextField(blank=True)),
                ("estimated_duration", models.CharField(max_length=100)),
                ("delivery_date", models.DateField()),
                ("quote_document", models.FileField(upload_to="quotations/responses/")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "quotation",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="response",
                        to="quotations.quotation",
                    ),
                ),
            ],
            options={
                "verbose_name": "Quotation Response",
                "verbose_name_plural": "Quotation Responses",
            },
        ),
    ]
